version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: shopflow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopflow
    ports:
      - "3306:3306"
    volumes:
      - shopflow-mysql-data:/var/lib/mysql

volumes:
  shopflow-mysql-data: