ALTER TABLE users ADD COLUMN phone_number VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN address VARCHAR(500) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';